zones:
  - id: arceology
    status:
      pc_1: 200
  - id: katerina
    status:
      pc_1: 200
  - id: empire
    status:
      pc_1: 200
  - id: mine
    status:
      pc_1: 200
  - id: guards
    status:
      pc_1: 200
  - id: war
    status:
      pc_1: 200
      pj_1: 0
  - id: vov
    status:
      pc_1: 200
  - id: map
    status:
      pc_1: 200
      pj_1: 0
  - id: ussr
    status:
      pc_1: 200
  - id: facade
    status:
<<<<<<< HEAD
      pc_1: 200
=======
      pc_1: 200
>>>>>>> 211e20eb4cd0122c054df2e790a932e69d3b7bca
