lightVase:
  out: A
  lights:
    - address: 4
      default: 245
    - address: 8
      default: 220
    - address: 27
      default: 220
    - address: 33
      default: 245
    - address: 37
      default: 245
    - address: 50
      default: 220
    - address: 51
      default: 240
    - address: 53
      default: 240
    - address: 58
      default: 240

lightShowcase1:
  out: B
  lights:
    - address: 1
      default: 220
    - address: 6
      default: 220
    - address: 16
      default: 180

lightPlatform2:
  out: B
  lights:
    - address: 4
      default: 229
    - address: 5
      default: 240
    - address: 8
      default: 220
    - address: 9
      default: 220
    - address: 11
      default: 240
    - address: 12
      default: 240
    - address: 17
      default: 240

ligthTree:
  out: B
  lights:
    - address: 0
      default: 250
    - address: 3
      default: 240
    - address: 10
      default: 240
    - address: 15
      default: 254

lightZoya:
  out: B
  lights:
    - address: 2
      default: 235
    - address: 7
      default: 220
    - address: 14
      default: 240

lightFireworks:
  out: C
  lights:
    - address: 4
      default: 220
    - address: 2
      default: 220
    - address: 3
      default: 240
    - address: 9
      default: 220
    - address: 1
      default: 220
    - address: 8
      default: 250
    - address: 0
      default: 240

lightStars:
  out: C
  lights:
    - address: 5
      default: 229
    - address: 7
      default: 240
    - address: 6
      default: 220

lightShowcase21:
  out: A
  lights:
    - address: 30
      default: 190
    - address: 40
      default: 220
    - address: 41
      default: 220

lightShowcase22:
  out: A
  lights:
    - address: 2
      default: 220
    - address: 5
      default: 220
    - address: 22
      default: 220
    - address: 26
      default: 220
    - address: 35
      default: 190

lightShowcase23:
  out: A
  lights:
    - address: 0
      default: 220
    - address: 39
      default: 220

lightShowcase31:
  out: A
  lights:
    - address: 9
      default: 220
    - address: 14
      default: 160
    - address: 21
      default: 220
    - address: 47
      default: 160
    - address: 55
      default: 160
    - address: 56
      default: 157

lightShowcase32:
  out: A
  lights:
    - address: 10
      default: 189
    - address: 20
      default: 190
    - address: 49
      default: 190

lightShowcase33:
  out: A
  lights:
    - address: 3
      default: 170
    - address: 6
      default: 160
    - address: 18
      default: 220
    - address: 32
      default: 160
    - address: 54
      default: 220

lightGru:
  out: A
  lights:
    - address: 23
      default: 220
    - address: 24
      default: 201
    - address: 52
      default: 224

lightCoridor:
  out: A
  lights:
    - address: 12
      default: 194

lightPlatform3:
  out: A
  lights:
    - address: 11
      default: 240
    - address: 15
      default: 220
    - address: 16
      default: 240
    - address: 31
      default: 240
    - address: 34
      default: 240
    - address: 43
      default: 220
    - address: 45
      default: 240
    - address: 48
      default: 240
    - address: 57
      default: 240

lightPlatform4:
  out: A
  lights:
    - address: 7
      default: 240
    - address: 13
      default: 240
    - address: 19
      default: 240
    - address: 25
      default: 240
    - address: 36
      default: 220
    - address: 38
      default: 220
    - address: 42
      default: 239
    - address: 44
      default: 219
    - address: 46
      default: 240
    - address: 59
      default: 200
