led:
  out: A
  lights:
    - address: 0
      default: 245
    - address: 1
      default: 245
    - address: 3
      default: 245
    - address: 4
      default: 245
    - address: 5
      default: 245
    - address: 6
      default: 245
