zones:
  - id: reception
    status:
      pc_1: 520
  - id: entrance
    innerZones:
      - id: entranceLeft
        status:
          pc_1: 520
      - id: entranceRight
        status:
          pc_1: 520
  - id: mfc
    status:
      pc_1: 520
  - id: showHall
    status:
      pc_1: 520
      pj_1: 520
      pj_2: 520
      pj_3: 520
      pj_4: 520
      pj_5: 520
      pj_6: 520
      pj_7: 520
  - id: capture
    innerZones:
      - id: captureLeftTop
        status:
          pc_1: 520
          mc_1: 520
      - id: captureRightTop
        status:
          pc_1: 520
          mc_1: 520
      - id: captureLeftBottom
        status:
          pc_1: 520
          mc_1: 520
      - id: captureRightBottom
        status:
          pc_1: 520
          mc_1: 520
  - id: model
    status:
      pc_1: 520
      pj_1: 520
  - id: book
    status:
      pc_1: 520
  - id: sports
    status:
      pc_1: 520
      pj_1: 520
  - id: sportsTouch
    innerZones:
      - id: sportsTouchLeft
        status:
          pc_1: 520
      - id: sportsTouchMiddle
        status:
          pc_1: 520
      - id: sportsTouchRight
        status:
          pc_1: 520
  - id: literature
    status:
      pc_1: 520
      pj_1: 520
  - id: literatureTouch
    status:
      pc_1: 520
